version: '3.3'
services:
    api:
        container_name: 'api'
        build: './Server'
        ports:
            - '9000:9000'
        depends_on:
            - 'mongo'
        networks:
            - routertest
        env_file:
            - ./Server/.env.prod
    client:
        container_name: 'client'
        build: './Client'
        ports:
            - 80:80
        depends_on:
            - 'api'
        networks:
            - routertest
    mongo:
        image: 'mongo:latest'
        container_name: 'test-mongo'
        ports:
            - '27017:27017'
        networks:
            - routertest
networks:
    routertest:
        driver: bridge
